version: '3'
services: 
  onetimesecret: 
    image: "civisanalytics/onetimesecret:dockerized"
    ports: 
      - "80:7143"
    links:
      - "redis:redis"
    environment:
      - OTS_DOMAIN=civisanalytics.com
      - OTS_HOST=onetimesecret.civisanalytics.com
      - OTS_SSL=true
  redis:
    image: "redis:3.2"