version: '3'
services: 
  onetimesecret: 
    image: dhilgarth/onetimesecret
#    ports:
#      - "80:7143"
# Better use a reverse proxy like Traefik
    environment:
      - OTS_DOMAIN=sovarto.com
      - OTS_HOST=secrets.sovarto.com
      - OTS_SSL=true
      - REDIS_HOST=redis-ots
  redis-ots:
    image: "redis:3.2"